/**
 * Generates a Material Design 3 style tonal color system as Tailwind v4
 * CSS custom properties, from three seed colors (primary / secondary /
 * tertiary). See ../README.md for the role list and how to use this.
 *
 * Usage:
 *   npm run generate               # reads src/seeds.json, prints CSS
 *   npm run generate -- seeds.json # reads a different seeds file
 */
import * as fs from 'fs';
import {buildScheme, corePaletteFromSeeds, Roles, Seeds} from './scheme.js';

function toCssBlock(roles: Roles, indent: string): string {
  return Object.entries(roles)
      .map(([role, hex]) => `${indent}--color-c-${role}: ${hex};`)
      .join('\n');
}

function main() {
  const seedsPath = process.argv[2] ?? new URL('../../src/seeds.json', import.meta.url).pathname;
  const seeds: Seeds = JSON.parse(fs.readFileSync(seedsPath, 'utf8'));

  const basePath = new URL('../../app/src/base.css', import.meta.url);
  const baseCss = fs.readFileSync(basePath, 'utf8');

  const core = corePaletteFromSeeds(seeds);

  const dark = buildScheme(core, seeds, true);
  const light = buildScheme(core, seeds, false);

  const out = `/* Generated by ponkotsu-css. */
@import 'tailwindcss';

@theme {
    --color-*: initial;
${toCssBlock(dark, '    ')}
}

[data-theme='light'] {
${toCssBlock(light, '    ')}
}

${baseCss}`;
  process.stdout.write(out);
}

main();
